/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testprojekt;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Molly
 */
public class BjudaIn extends javax.swing.JFrame {

    /**
     * Creates new form BjudaIn
     */
    String uid; 
    InfDB idb;
    Validator validator;
    
    public BjudaIn(String userID) {
        initComponents();
         uid = userID; 
         idb = TestProjekt.getDB();
         validator = new Validator();
         showMeetings();
         setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtattbjuda = new javax.swing.JTextField();
        cbMeetings = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Välj möte");

        jButton1.setText("Skicka inbjudan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Användare att bjuda in (användarnamn) ");

        txtattbjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtattbjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtattbjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMeetings, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMeetings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtattbjuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showMeetings() {
        try {
            String query = "select mid, amne from mote where anvandar_ID = " + uid;
            ArrayList<HashMap<String, String>> meetings = idb.fetchRows(query);
            for (HashMap<String, String> meeting : meetings) {
                String display = meeting.get("MID") + ": " + meeting.get("AMNE");
                cbMeetings.addItem(display);
            }
        } catch (InfException ie) {
            System.out.println(ie.getMessage());
        }
    }
    
    public String findUserID(String username) {    
        String result = "";
        try {
            String query = "SELECT Anvandar_ID FROM Anvandare WHERE Anvandar_namn = '" + username + "'";
            result = idb.fetchSingle(query);
        } catch(InfException ie) {
                System.out.println(ie.getMessage());
        }
        return result;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //String moteidd = txtmoteid.getText();
        String attbjuda = txtattbjuda.getText();
        String string = cbMeetings.getSelectedItem().toString();
        String meetingID = string.substring(0, string.indexOf(":"));

        try {
            if (validator.validateInvite(meetingID, attbjuda, uid)) {
                System.out.println("INSERT INTO inbjudningar VALUES (" + findUserID(attbjuda) + ", " + meetingID + ")");
                idb.insert("INSERT INTO inbjudningar VALUES (" + findUserID(attbjuda) + ", " + meetingID + ")");
                JOptionPane.showMessageDialog(null, "Inbjudan skickad");
            }
        } catch(InfException e) {
            System.out.println(e.getMessage());
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtattbjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtattbjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtattbjudaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMeetings;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtattbjuda;
    // End of variables declaration//GEN-END:variables
}
