/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testprojekt;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author isakj
 */
public class Comments extends javax.swing.JFrame {
    
    Validator validator;
    String postID;
    String userID;
    InfDB idb;

    /**
     * Creates new form Comments
     */
    public Comments(String postID, String userID) {
        initComponents();
        this.postID = postID;
        this.userID = userID;
        validator = new Validator();
        System.out.println(userID);
        idb = TestProjekt.getDB();
        pnlNewComment.setVisible(false);
        pnlComments.setVisible(true);
        displayComments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlComments = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextPane();
        pnlNewComment = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnComment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Kommentera");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtComments.setEditable(false);
        txtComments.setContentType("text/html");
        txtComments.setText("<html><b>Andreas</b><br>\nKommentar\n</html>");
        jScrollPane3.setViewportView(txtComments);

        javax.swing.GroupLayout pnlCommentsLayout = new javax.swing.GroupLayout(pnlComments);
        pnlComments.setLayout(pnlCommentsLayout);
        pnlCommentsLayout.setHorizontalGroup(
            pnlCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCommentsLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton1)
                .addContainerGap(156, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        pnlCommentsLayout.setVerticalGroup(
            pnlCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCommentsLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        txtText.setColumns(20);
        txtText.setLineWrap(true);
        txtText.setRows(5);
        txtText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtText);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("0");

        jLabel2.setText("/200");

        btnComment.setText("Kommentera");
        btnComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewCommentLayout = new javax.swing.GroupLayout(pnlNewComment);
        pnlNewComment.setLayout(pnlNewCommentLayout);
        pnlNewCommentLayout.setHorizontalGroup(
            pnlNewCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewCommentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNewCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewCommentLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(pnlNewCommentLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(btnComment)
                        .addGap(67, 67, 67))))
        );
        pnlNewCommentLayout.setVerticalGroup(
            pnlNewCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewCommentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(btnComment))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNewComment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlComments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNewComment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlComments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentActionPerformed
       
        String newComment = txtText.getText();
        try {
            if (validator.validateComment(newComment)) {
                int kid = 0;
                if (idb.fetchSingle("SELECT count (*) FROM KOMMENTAR").equals("0")) {
                    kid = 1;
                } else {
                    String maxKid = idb.fetchSingle("SELECT max (kid) FROM KOMMENTAR");

                    int maxKaidInt = Integer.parseInt(maxKid);
                    kid = maxKaidInt + 1;


                }
                String query = "insert into Kommentar values ('" + newComment + "', " + kid + "," + postID + "," + userID + ")";

                idb.insert(query);

                pnlNewComment.setVisible(false);
                pnlComments.setVisible(true);
                displayComments();
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    
    }//GEN-LAST:event_btnCommentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pnlComments.setVisible(false);
        pnlNewComment.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void displayComments() {
        try {
            if (!idb.fetchSingle("SELECT Count(*) from Kommentar WHERE InlaggsID = " + postID).equals("0")) {
                String query = "SELECT * FROM Kommentar WHERE InlaggsID = " + postID;
                ArrayList<HashMap<String, String>> comments = idb.fetchRows(query);
                String commentField = "<html>";
                for (HashMap<String, String> comment : comments) {
                    String userName = findUserName(comment.get("ANVANDAR_ID"));
                    String text = comment.get("TEXT");
                    commentField += "<b>" + userName + "</b><br>" + text + "<br><br>";
                }
                commentField += "</html>";
                txtComments.setText(commentField);
            } else {
                txtComments.setText("Inga kommentarer att visa");
            }
        } catch(InfException ie) {
        
        }
    } 

    public String findUserName(String id) {    
        String result = "";
        try {
            String query = "SELECT Anvandar_namn FROM Anvandare WHERE Anvandar_ID = '" + id + "'";
            result = idb.fetchSingle(query);
        } catch(InfException ie) {
                
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlComments;
    private javax.swing.JPanel pnlNewComment;
    private javax.swing.JTextPane txtComments;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables
}
