/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testprojekt;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Mollyyy
 */
public class PersonligProfil extends javax.swing.JFrame {

    /**
     * Creates new form PersonligProfil
     */
    
    String uid; 
    InfDB idb;
     
    public PersonligProfil(String userID) {
        initComponents();
        uid = userID; 
        idb = TestProjekt.getDB();
        setCategoryCbs();
        System.out.println(uid); 
        updateCategoryList();
        lbl.setToolTipText("Välj kategorier att sortera blogginlägg utifrån");
        
     
        
    }
    

//            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnamn = new javax.swing.JTextField();
        txttele = new javax.swing.JTextField();
        txtepost = new javax.swing.JTextField();
        txtannamn = new javax.swing.JTextField();
        txtlosen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblandrat = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCategoryList = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Namn: ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Användarnamn:");

        jLabel3.setFont(new java.awt.Font("Verdana Pro", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Personlig profil");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("E-postadress:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Telefonnummer:");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Lösenord:");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testprojekt/Images/liten.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        txtnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamnActionPerformed(evt);
            }
        });

        txttele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleActionPerformed(evt);
            }
        });

        txtlosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlosenActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setText("Spara ändring");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblandrat.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSave.setText("Lägg till");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listCategoryList);

        jButton2.setText("Ta bort");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Valda kategorier");

        jLabel9.setText("Favoritkategorier");

        lbl.setText("(?)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl)
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnamn)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtlosen)
                                    .addComponent(txtannamn)
                                    .addComponent(txtepost)
                                    .addComponent(txttele))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblandrat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txttele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtepost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtannamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtlosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblandrat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
            
//         

        String nuvarandeAnvandarId = uid; 
        
        
        //NAMN
         
          String svarEtt = "Tom";
          String fragaEtt = "SELECT NAMN FROM ANVANDARE WHERE ANVANDAR_ID = " + nuvarandeAnvandarId;
         
         
           try {
            svarEtt = idb.fetchSingle(fragaEtt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!" + e.getMessage());
        }
           
             
           txtnamn.setText(svarEtt);
           
           
           
           //TELEFON
           
           String svarTva = "Tom"; 
           String fragaTva = "SELECT TELE FROM ANVANDARE WHERE ANVANDAR_ID = " + nuvarandeAnvandarId; 
           
        try {
            svarTva = idb.fetchSingle(fragaTva);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!" + ex.getMessage()); 
            Logger.getLogger(PersonligProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        txttele.setText(svarTva);
        
        
        //EPOST
        
        String svarTre = "tom"; 
        String fragaTre = "SELECT EPOST FROM ANVANDARE WHERE ANVANDAR_ID = " + nuvarandeAnvandarId; 
        
        try {
            svarTre = idb.fetchSingle(fragaTre);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!" + ex.getMessage()); 
            Logger.getLogger(PersonligProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtepost.setText(svarTre);
        
        //AnvänDARNAMN 
        
        String svarFyra = "tom"; 
        String fragaFyra = "SELECT ANVANDAR_NAMN FROM ANVANDARE WHERE ANVANDAR_ID = " + nuvarandeAnvandarId; 
        
        try {
            svarFyra = idb.fetchSingle(fragaFyra);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!" + ex.getMessage()); 
            Logger.getLogger(PersonligProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtannamn.setText(svarFyra);
        
        //LOSEN
        
        String svarFem = "tom"; 
        String fragaFem = "SELECT LOSEN FROM ANVANDARE WHERE ANVANDAR_ID = " + nuvarandeAnvandarId; 
        
        try {
            svarFem = idb.fetchSingle(fragaFem);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!" + ex.getMessage()); 
            Logger.getLogger(PersonligProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtlosen.setText(svarFem);
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        //String nuvarandeAgentId = txtSokaPaAgent.getText();
        //txtSokaPaAgent.setText(nuvarandeAgentId);
        
        //ÄNDRANAMN
        
         String nyttNamn = txtnamn.getText(); 
        
        try {
            
            String id = uid; 
            this.idb.update("UPDATE ANVANDARE SET NAMN = '" + nyttNamn + "' WHERE ANVANDAR_ID =" + id);
            
        } catch (InfException ex) {
            java.util.logging.Logger.getLogger(PersonligProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //ÄNDRATELEFONNUMMER 
        
         String nyttTele = txttele.getText(); 
        
        try {
            
            String id = uid; 
            this.idb.update("UPDATE ANVANDARE SET TELE = '" + nyttTele + "' WHERE ANVANDAR_ID =" + id);
            
        } catch (InfException ex) {
            java.util.logging.Logger.getLogger(PersonligProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //ÄNDRAEPOST
        
         String nyttEpost = txtepost.getText(); 
        
        try {
            
            String id = uid; 
            this.idb.update("UPDATE ANVANDARE SET EPOST = '" + nyttEpost + "' WHERE ANVANDAR_ID =" + id);
            
        } catch (InfException ex) {
            java.util.logging.Logger.getLogger(PersonligProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //ÄNDRAANVANDARNAMN
        
        //ÄNDRAANVANDARNAMN
        
        
        String nyttAnnamn = txtannamn.getText();
        
       
        String id = uid;
        try {
           
            this.idb.update("UPDATE ANVANDARE SET ANVANDAR_NAMN = '" + nyttAnnamn + "' WHERE ANVANDAR_ID =" + id);
        } catch (InfException ex) {
            Logger.getLogger(PersonligProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //ÄNDRALOSEN
        
        String nyttLosen = txtlosen.getText(); 
        
         try {
            

            this.idb.update("UPDATE ANVANDARE SET LOSEN = '" + nyttLosen + "' WHERE ANVANDAR_ID =" + id);
            
        } catch (InfException ex) {
            java.util.logging.Logger.getLogger(PersonligProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        lblandrat.setText("Du har nu ändrat!");
         
         
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtlosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlosenActionPerformed

    private void txtnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamnActionPerformed

    private void txtteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String category = cbCategory.getSelectedItem().toString();
        try {
            if (!category.equals("-- Kategori --")) {
                String id = findCategoryID(category);
                String query = "Insert into Anvandare_Kategori values (" + uid + "," + id + ")";
                idb.insert(query);
                updateCategoryList();
            }
        } catch (InfException ie) {

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (listCategoryList.getSelectedValue() != null) {
            String categoryID = findCategoryID(listCategoryList.getSelectedValue());
            try {
                String query = "delete from anvandare_kategori where kategori = " + categoryID + " and anvandare =" + uid;
                idb.delete(query);
                updateCategoryList();
            } catch(InfException ie) {
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void updateCategoryList() {
        try {
            int amount = Integer.parseInt(idb.fetchSingle("select count(*) from anvandare_kategori where anvandare = " + uid));
            DefaultListModel listModel = new DefaultListModel();
            if (amount > 0) {
                String query = "select kategori from anvandare_kategori where anvandare = " + uid;
                ArrayList<String> categories = idb.fetchColumn(query);
                for (String category : categories) {
                    listModel.addElement(findCategoryName(category));
                }
            }
            listCategoryList.setModel(listModel);
        } catch (InfException ie) {

        }
    }
    
    public String findCategoryID(String namn) {
        String query = "Select KAID from Kategori where namn = '" + namn + "'";
        String result = "";
        try {
            result = idb.fetchSingle(query);
        } catch (InfException ie) {
            System.out.println(ie.getMessage());
        }
        return result;
    }
    
    public String findCategoryName(String id) {
        String query = "Select Namn from Kategori where KAID = " + id;
        String result = "";
        try {
            result = idb.fetchSingle(query);
        } catch (InfException ie) {
            System.out.println(ie.getMessage());
        }
        return result;
    }

    public void setCategoryCbs(){ 
        try {
            
            if(idb.fetchSingle("SELECT count (*) FROM KATEGORI").equals("0")){
            
            }
            else{
            ArrayList<String> kategorier = idb.fetchColumn("SELECT namn FROM KATEGORI");
            DefaultComboBoxModel kategori = new DefaultComboBoxModel();
            kategori.addElement("-- Kategori --");
            for(String listaKategorier : kategorier){
                kategori.addElement(listaKategorier);
            
           }
            cbCategory.setModel(kategori);
            }
        } catch (InfException ex) {
            Logger.getLogger(BlogV2.class.getName()).log(Level.SEVERE, null, ex);
        }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblandrat;
    private javax.swing.JList<String> listCategoryList;
    private javax.swing.JTextField txtannamn;
    private javax.swing.JTextField txtepost;
    private javax.swing.JTextField txtlosen;
    private javax.swing.JTextField txtnamn;
    private javax.swing.JTextField txttele;
    // End of variables declaration//GEN-END:variables
}
